### ISSUE TITLE
Angular2 and PaperJs 

### ISSUE THREAD

**Issue by Govi-p** [clark-stevenson/paper.d.ts#17]
I included npm package paper by giving "npm install paper". The package got added.
I wants to draw a line using paperJS. How it will be done in typescript?

**Comment by clark-stevenson** [comment]
Sorry for the long delay 👎 

I just recently was using Angular recently.  

You need to also install `npm install --save-dev @types/paper`

That will get you the Typescript declarations and give you auto complete.

Be aware though that this declaration is almost 4 years outdated and 2 versions behind the paper.js project.
