### ISSUE TITLE
How do I import from it?

### ISSUE THREAD

**Issue by makoConstruct** [clark-stevenson/paper.d.ts#2]
given

```
/// <reference path="./paper.d.ts"/>
```

any of

```
import {Path} from "paper"
import {Path} from paper
import {Path} from "./paper"
```

Will not work.
If I change paper.d.ts to

```
declare module "paper" {
```

(declaring with a string literal), then the first import syntax will work. However, there will be no `paper` object, so I'm not sure that's any good.

I guess another way of putting it would be.. How do I use it?

**Comment by michaelsmithson** [comment]
I had to make a few changes to get it to work.
- Rename the current module to paperModule (not sure if this was necessary)
- Add a second module to export that module as the default

```
declare module "paper" {
  export default paperModule
}
```
- Then we can import the paper object successfully:

`import paper from "paper";
`

and you can use paper.Point etc.

**Comment by makoConstruct** [comment]
Really? Because paper-core.js (at least when you're importing in amd `define` style) doesn't write to `exports.default`, so `import paper from './paper'` breaks the module loader(in my case, require.js). Paper instead returns an export object, and the only way that I can see to work with that is to move everything in paper.d.ts to the root scope and import it like `import * as paper from "./paper"`

I've also had to add

``` javascript
export class PaperInstallation {
    Matrix: typeof Matrix
    Point: typeof Point
    Rectangle: typeof Rectangle
    Size: typeof Size
    PaperScope: typeof PaperScope
    Item: typeof Item
    ...
}
```

to add typing for `paperScope.install(obj)` (and it's still all a bit messy because PaperInstallations don't actually exist so you have to `var pap = {} as PaperInstallation; paper.install(pap); pap.Path(..etc`)

**Comment by makoConstruct** [comment]
Oh.. `paper` has the classes installed to it. That information is not where I'd expect it to be in the documentation (I just looked at the "properties" sections of the PaperScope class and found no mention of any class members, and took that to mean that, you know,, it wouldn't be totally full of class members). No wonder nobody bothered with PaperInstallations.

**Comment by michaelsmithson** [comment]
We are using jspm/systemjs rather than require, so that could be the behavior difference. Unfortunately I can't say I know enough about the different module loaders to really know what I am talking about.

**Comment by clark-stevenson** [comment]
Guys this is over my head for sure.  I never got to use paper in the end because the project was cancelled :-1: 

But I think @beeker has the right idea. 

```
declare module "paper" {
  export default paperModule
}
```

Is essential in some way. 

For example, with Pixi  which I am more familiar with, this line of code was essential. (Where PIXI is equivalent to paperModule i guess).

```
declare module 'pixi.js' {
    export = PIXI;   
}

```

One of the reasons I am apprehensive is because my pixi version there, and @beeker fix is doing something very similar, but not identical and I cannot pretend to know the difference between `=` and `default`. 

None the less  with pixi , those lines unlocked SystemJS capability (and I guess Require?).

`import {Sprite, Container} from "pixi.js"`

**Comment by makoConstruct** [comment]
Yeah, it'd be the same as paper.js: exporting straight into the `exports` object instead of `exports.default`. If you tell typescript to expect it to be in `exports.default` (eg, by declaring `export default PIXI` in the d.ts), many module loaders will not find anything there.

For me,

```
declare module "paper"{
    export = paper
}

declare module paper {
    ...
```

works no better than

```
declare module "paper" {
    ...
```

So the fix is very simple. Put quotes around the module name in the d.ts, then import it like `import {Point, Path} from "paper"` or `import * as paper from "paper"`.

**Comment by clark-stevenson** [comment]
@elektrowolle  did extactly what @makoConstruct  suggested on #4 ! Thanks for your efforts :+1:
