### ISSUE TITLE
style assignments reporting error when using 'any' 

### ISSUE THREAD

**Issue by martinmeeser** [clark-stevenson/paper.d.ts#21]
Thank you very much for providing those types.
Excellent work!

This came to my attention: 

```
let simpleLine: paper.Path.Line = new paper.Path.Line(paper.view.center, paper.view.center.add([10,10]));
simpleLine.style = { strokeColor: 'hsla(207, 100%, 33%, 1)', strokeWidth: 4 }; // reported as error, but valid and working
```

simpleLine.style: paper.Style | any

I use this often because it saves a lot of typing and I find it more readable.

Reference: [paperjs](http://paperjs.org/reference/style/)

**Comment by martinmeeser** [comment]
or second thought is: every field in class paper.Style must be optional

**Comment by clark-stevenson** [comment]
Hey @martinmeeser  thanks! 👍 

I would totally agree that those should be optional.  The problem I am facing in this Repository is that this was pushed to `definitely typed` and now there is 2 competing declarations. In your case both are broken. 

I will solve this problem and that competing problem tonight when I get home, update this repo and DT, and then mothball this version.

That way `npm install @types/paperjs --save-dev`  will always be the main file in the future which everyone needs.
