### ISSUE TITLE
Merge into DefinitelyTyped

### ISSUE THREAD

**Issue by sqwk** [clark-stevenson/paper.d.ts#5]
Would it be OK to merge these definitions into the DefinitelyTyped project, from where they might also be published to npm at @types/paper?

**Comment by clark-stevenson** [comment]
Go for it! I don't think I will be using it any time soon, and it will only grow stale if it remains here.

**Comment by sqwk** [comment]
Test files are still missing: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10691

**Comment by clark-stevenson** [comment]
One of the reasons I don't do DT is because of all this test stuff.  I don't know what it means....

**Comment by sqwk** [comment]
I have the same problem. It's out there now though, maybe somebody chimes in …

**Comment by sqwk** [comment]
The defs have been merged into the DefinitelyTyped project and can now be fetched here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/paper

**Comment by clark-stevenson** [comment]
Thanks @sqwk  👍
