### ISSUE TITLE
Incorect definition for paper.Path.Rectangle | Line | Circle...

### ISSUE THREAD

**Issue by sasensi** [clark-stevenson/paper.d.ts#8]
Hi,

first of all, thank you for this definition that helps me starting a new project using typescript and paperjs.

Experimenting with it, I found that paper.Path.* static properties throw an error when trying to instantiate it as you would do with paperjs API.

```
new paper.Path(); // works as expected
new paper.Path.Rectangle(); // throws an error
```

I've searched ways to resolve it but I'm just starting with typescript and I didn't find any ways to use class static property as a constructor for another class.

Have you got an idea ?

Thank you.

**Comment by sasensi** [comment]
I managed fixing it myself.

https://github.com/clark-stevenson/paper.d.ts/pull/9

**Comment by clark-stevenson** [comment]
Thanks, I don't use these any more but I get PRs now and again for those that do. I appreciate it 👍
